version: '3.8'
services:
  mysql_srv:
    image: mysql:8.0
    container_name: mysql_ctr
    stdin_open: true
    restart: always
    environment:
      MYSQL_DATABASE: stock_app
      MYSQL_ROOT_PASSWORD: Ilikepie9!
    ports:
      - "3307:3306"
    volumes:
      - ./data:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
      - ./logs:/logs

  phpmyadmin_srv:
    depends_on:
      - mysql_srv
    image: phpmyadmin/phpmyadmin
    container_name: phpadmin_ctr
    restart: always
    environment:
      PMA_HOST: mysql_srv
    ports:
      - "8080:80"

  backend_srv:
    build:
      context: ./server
    depends_on:
      - mysql_srv
    environment:
      MYSQL_HOST_IP: mysql_srv
      MYSQL_USER: root
      MYSQL_DATABASE: stock_app
      MYSQL_PASSWORD: Ilikepie9!
    ports:
      - "3001:3001"
    volumes:
      - ./server:/server

  frontend_srv:
    build:
      context: ./client
    ports:
      - "3000:80"
    volumes:
      - ./client:/client

volumes:
  mysql_srv:
    driver: local